module AppIconsHelper	
	def controller_icon
		{
			'usuarios' => 'person',
			'app_versiones' => 'gear',
			'app_nominas' => 'person-workspace',
			'aut_tipo_usuarios' => 'file-person',
			'app_archivos' => 'file',
			'app_enlaces' => 'box-arrow-up-right',
			'clientes' => 'building',
			'empresas' => 'buildings',
			'causas' => 'journal-text',
			'asesorias' => 'briefcase',
			'cargos' => 'currency-dollar',
			'tablas' => 'table',
			'regiones' => 'geo-alt',
			'tipo_causas' => 'file-check',
			'tribunal_cortes' => 'bank',
			'hechos' => 'check2-circle',
			'tar_aprobaciones' => 'check-all',
			'tar_facturaciones' => 'coin',
			'tar_facturas' => 'receipt',
			'tar_tarifas' => 'cash-coin',
			'tar_servicios' => 'cash-coin',
			'tar_detalle_cuantias' => 'check2-square',
			'tar_valor_cuantias' => 'currency-dollar',
			'tar_uf_sistemas' => 'calendar3',
			'tar_uf_facturaciones' => 'currency-dollar',
			'tar_pagos' => 'currency-dollar',
			'tar_formulas' => 'lightbulb',
			'tar_comentarios' => 'chat',
			'st_modelos' => 'box',
			'dt_materias' => 'bank',
			'm_periodos' => 'calendar3',
			'm_modelos' => 'piggy-bank',
			'm_cuentas' => 'safe2',
			'm_formatos' => 'file-spreadsheet',
			'app_empresas' => 'buildings',
			'app_directorios' => 'folder',
			'app_escaneos' => 'images',
			'm_bancos' => 'bank',
			'age_actividades' => 'calendar4-event',
			'age_usuarios' => 'person-workspace',
			'age_pendientes' => 'list-check',
			'cal_annios' => 'calendar',
			'cal_meses' => 'calendar3',
			'cal_semanas' => 'calendar2-week',
			'cal_feriados' => 'calendar2-check',
			'notas' => 'list-check',
			'pautas' => 'bar-chart',
			'cuestionarios' => 'question-square',
			'preguntas' => 'question',
			'lgl_documentos' => 'blockquote-left',
			'lgl_parrafos' => 'blockquote-right',
			'productos' => 'box-seam',
			'com_documentos' => 'file-earmark-pdf',
			'krn_denuncias' => 'mailbox',
			'krn_investigadores' => 'binoculars',
			'krn_empresa_externas' => 'building',
			'krn_tipo_medidas' => 'exclamation-triangle',
			'procedimientos' => 'bar-chart-steps',
			'dt_tabla_multas' => 'table',
			'slides' => 'file-slides'
#			'rep_archivos' => 'file-earmark-richtext'
		}
	end
end